# Generated by Django 3.2.23 on 2024-01-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_category_options'),
        ('accounts', '0004_auto_20240121_1751'),
    ]

    operations = [
    ]
